
export const TABS = {
    WELCOME: "WELCOME",
    PURCHASES: "PURCHASES",
    SALES: "SALES",
    CATALOGUE: "CATALOGUE",
    FAVOURITE: "FAVOURITE",
    COMPARE:"COMPARE"
};

export const PAGE_SIZE = 5;