
export const TABS = {
    WELCOME: "WELCOME",
    PURCHASES: "PURCHASES",
    SALES: "SALES",
    CATALOGUE: "CATALOGUE",
    FAVOURITE: "FAVOURITE",
    COMPARE:"COMPARE",
    PERFORMANCE:"PERFORMANCE",
    PROJECTS : "PROJECTS"
};

export const PAGE_SIZE = 5;